### ISSUE TITLE
Add image output API

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js-jupyter#15]
Add a method to output a png and/or svg file.  See issue #1

**Comment by a-slide** [comment]
Hi Jim,
Thanks a lot for this new version. I gave it a try this morning and it is much better than the previous one.
Regarding the image output the rendering is great but for svg the picture extends outside of the image frame (when opening with inkscape for example).
A nice feature would also be to have a output of the entire widget and not only the selected track.

Thanks again
Adrien

**Comment by jrobinso** [comment]
@a-slide  There is a function on igv.js browser to create an svg document for the entire browser (widget).  The object of this ticket is to expose it, something like

b.to_svg()

However, where should the output go?   Probably a file, not in cell output.   We could open a file dialog from the browser to "download" it as we do now in the popup menus,  or return it to python using a Comms message and deal with it there.   Any thoughts on the right mechanism?

**Comment by jrobinso** [comment]
@a-slide Actually maybe cell output would be useful, then it could be saved.   I suffer from having zero experience using a notebook myself and don't really have a feel for how people would use this.

**Comment by jrobinso** [comment]
OK, makes sense.    Without resorting to hacks it looks like the only legit
way to export cell output is from the server (python).   So this might
entail sending SVG to the server via a Comms message, only for the server
to send it back to the client (via whatever mechanism they use) to be
inserted in the DOM.    I can't find any documentation on manipulating the
DOM from an nbextension.   If running client and server on the same
machine,  which I think is how most people run notebooks,  this really
won't matter.

**Comment by jrobinso** [comment]
I've implemented this but it requires 2 function calls
(1)  browser.get_svg()
(2) browser.display_svg()

The first sends a message to the front end to create an SVG image representing the current view.   The SVG is then sent to the server (python) via a message and stored on the "Browser" object.   The second call displays the browser in the cell.   2 calls are necessary because the messages are 1-way and asynchronous.   If anyone knows a way to do this with a single call I would welcome a PR.
