### ISSUE TITLE
multiple bigwigs in one track?

### ISSUE THREAD

**Issue by sunworshipper** [igvteam/igv.js-jupyter#22]
Hi,

I love the jupyter integration.  Works very well!
Is multiple file source overlay in one track possible?
I am looking to overlay bigwig data.

kind regards

**Comment by jrobinso** [comment]
Thanks, and thanks for being an early adopter.  I am not active in the python or jupyter communities so feedback is especially important.

The following should work for the object you send to loadTrack.   In general you can use any options described here for tracks, although in this case the merged option is not yet documented:  https://github.com/igvteam/igv.js/wiki/Tracks-2.0

```
{
			"type": "merged",
			"name": "Overlay",
			"height": 50,
			"tracks": [
				{
					"url": "http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeBroadHistone/wgEncodeBroadHistoneGm12878H3k27me3StdSigV2.bigWig",
					"name": "GM12878 H3K27me3 ChipSeq Signal",
					"color": "rgb(200,0,0)"
				},
				{
					"url": "http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeBroadHistone/wgEncodeBroadHistoneGm12878H3k36me3StdSig.bigWig",
					"name": "GM12878 H3K36me3 ChipSeq Signal",
					"color": "rgb(0,0,150)"
				},
				{
					"url": "http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeBroadHistone/wgEncodeBroadHistoneGm12878H3k4me3StdSig.bigWig",
					"name": "GM12878 H3K4me3 ChipSeq Signal",
					"color": "rgb(0,150,0)"
				}
			]
		}
```

**Comment by sunworshipper** [comment]
<img width="1033" alt="screen shot 2019-01-22 at 11 49 09 pm" src="https://user-images.githubusercontent.com/8853848/51573321-b3b38c80-1ea0-11e9-9913-d9092526225c.png">
Exactly what I was looking for! Thank you!
