### ISSUE TITLE
how would I actually view the plot?

### ISSUE THREAD

**Issue by KhagayN** [igvteam/igv.js-jupyter#4]
I'm able to run this code from the example but, how would I go about viewing the plot?

`# Define IGV.js instance`
`from igv import IGV, Reference, Track`

`IGV(locus="chr12:98,997,292-98,997,392", reference=Reference(id="hg19"), tracks=[
    Track(name="Genes", format="bed",       url="//s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/gencode.v18.collapsed.bed", display_mode="EXPANDED"), Track(name="Brain (BodyMap)", format="bam", url="//data.broadinstitute.org/igvdata/BodyMap/hg19/IlluminaHiSeq2000_BodySites/brain_merged/accepted_hits.bam")])`

**Comment by KhagayN** [comment]
`print hello`

**Comment by turner** [comment]
Each notebook is composed of executable cells. Click a cell to see a result.

**Comment by turner** [comment]
Each notebook is composed of executable cells. To execute (run) a cell
1) select it (a left hand blue border appears to indicate selection)
2) click the play button (or shift-enter)

Here is a screen shot of play button.

![foo](https://cloud.githubusercontent.com/assets/87169/18177425/2dd1e6d8-7048-11e6-9b9c-5933db384872.png)

Here is a screen shot of API Examples notebook where I have selected the first cell.
![screen shot 2016-09-01 at 1 19 56 pm](https://cloud.githubusercontent.com/assets/87169/18177433/344d5826-7048-11e6-8722-48ec89c3f9f2.png)

**Comment by KhagayN** [comment]
Thank you for the quick reply! Unfortunately, I followed your instructions and a plot still does not appear. 

![screen shot 2016-09-01 at 1 38 33 pm](https://cloud.githubusercontent.com/assets/8751865/18177732/7d56ddb6-7049-11e6-99bc-535c839dd307.png)

**Comment by turner** [comment]
Can you run **any** notebooks in Jupyter?

**Comment by KhagayN** [comment]
Yes, I can run certain lab analyses in Jupyter notebook.s

**Comment by tmtabor** [comment]
One possibility is that you haven't enabled the nbextension yet. Assuming that you've installed the igv python package, if you go to your command line and run the following two commands, it will enable support for the plots in the notebook environment.

> jupyter nbextension install --py igv
> 
> jupyter nbextension enable --py igv

**Comment by KhagayN** [comment]
I've installed and enabled the extension. I listed the extensions enabled below. Maybe there's a problem because there's a problem validating? 

![screen shot 2016-09-01 at 1 38 33 pm](https://cloud.githubusercontent.com/assets/8751865/18178183/5d2d7cf0-704b-11e6-9a06-9a808439d912.png)

**Comment by KhagayN** [comment]
![screen shot 2016-09-01 at 1 53 52 pm](https://cloud.githubusercontent.com/assets/8751865/18178242/8c2cc2ae-704b-11e6-9cdc-aeeb048756e2.png)

**Comment by tmtabor** [comment]
That would be why the plot is not displaying. The real question is why the nbextension isn't validating.

You might want to check your nbextension path just to make sure that the igv-jupyter.js file actually copied there successfully during installation. In my personal experience, I occasionally have trouble installing nbextensions due to file permission issues copying the file over in the first place.

On a Mac nbextensions will usually be installed to `~/Library/Jupyter/nbextensions/` or `/usr/local/share/jupyter/nbextensions/`. On Linux it's going to vary by distribution.

**Comment by jrobinso** [comment]
Hi @KhagayN ,  were you able to resolve your problem?

**Comment by KhagayN** [comment]
Yes @jrobinso. I had to contact people who had admin privileges to enable the extension. After that, I was able to load and use the package! Thanks for the help!
