### ISSUE TITLE
Bam reads are cutoff

### ISSUE THREAD

**Issue by jfear** [igvteam/igv.js-jupyter#8]
Hey guys, sorry to bug you again.

When loading a BAM file the reads appear to get cutoff. This happens with default setting, and I have played with the display_mode, height, maxRows, and samplingDepth parameters which do not fix the problem. 

![screen shot 2016-10-27 at 1 02 29 pm](https://cloud.githubusercontent.com/assets/1240432/19777371/e9b87136-9c45-11e6-9267-554e64ce9bd3.png)

thanks
Justin

**Comment by jrobinso** [comment]
Thanks for the report, we'll look into it.

**Comment by jrobinso** [comment]
BTW, keep bugging us.

**Comment by jfear** [comment]
I think I have narrowed the problem down. If I change the height attribute on the canvas it seems to look as expected. 

Before the change:

![screen shot 2016-10-27 at 2 39 37 pm](https://cloud.githubusercontent.com/assets/1240432/19780541/74c7d7e6-9c53-11e6-820a-be3752b6480a.png)


After the change:

![screen shot 2016-10-27 at 2 37 00 pm](https://cloud.githubusercontent.com/assets/1240432/19780549/7b62a8ba-9c53-11e6-931f-0f8bdcef636a.png)

Don't know if there is an attribute I should change when making the IGV object or the BAM track, or if this is a bug.

**Comment by turner** [comment]
Justin that's helpful. I'm looking at this now.

**Comment by jrobinso** [comment]
Thanks for the info,  I think its a bug on our side, you shouldn't have to
do that.  You should see a scrollbar when the alignments are "cut off",
 and also you should be able to control the height of the track in the
properties.

**Comment by turner** [comment]
I can not reproduce this issues. Are you seeing this with the examples as well. Try "BAM Example.ipynb"

**Comment by jfear** [comment]
Sorry, just saw that you had replied. 

I still get the same thing using the example notebook. I will play with it on some different computers and see if I can figure out if there is something specific to my setup. Nothing in the javascript console jumps out, so it maybe a chrome/osx thing. I will keep you posted.

**Comment by jrobinso** [comment]
To be clear the "cut off" alignments are normal, what's not normal is the
absence of a scrollbar in the track.   Also, setting track height should
work (it does for us).

**Comment by jfear** [comment]
Just to clarify. There is a scroll bar, but the bams are cutoff half way through the read. I can scroll down, but it is just white. 

![screen shot 2016-11-02 at 1 49 00 pm](https://cloud.githubusercontent.com/assets/1240432/19948138/82943b8a-a121-11e6-9db4-8cc4549efb0d.png)

I tried messing with the `height` and `maxHeight` parameters but they appear to do nothing. 

When I get a chance I will test on different browsers/machines and see if there is something strange with my set up.

**Comment by a-slide** [comment]
I believe this is solved in the last version of the package
